version: "3"
services:
    Echelon:
        image: encrypt65/echelon
        container_name: Echelon
        restart: unless-stopped
        volumes:
            - ./config.json:/usr/src/app/config.json
            - ./banners:/usr/src/app/banners
        network_mode: "host"
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
